### ISSUE TITLE
Father & Son: Monophonic possibility?

### ISSUE THREAD

**Issue by Deevje** [freddyz/computerscare-vcv-modules#31]
Hey there, first of all I want to thank you for your amazing modules! I find them really creative and inspiring, although I haven´t wrapped my head around all of them yet :) 

I was wondering if it would be possible to have an option in the menu to use Father & Son monophonically, the outputs simply summing the inputs they receive? I really like the snapshot/sequencing functionality of the module, but I tend to use patch matrices more like on the old EMS Synthi, which asks for monophony. If I could switch Father & Son to monophonic I would probably use it a lot!
I made a comparison video (no sound) to show what the different outcomes are when using Father & Son for the same purpose as for instance the Strum Mental Patch Matrix, Bogaudio's Matrix88 and Bidoo's ACnE:

https://www.youtube.com/watch?v=JXef_GQktf4

I'm hoping to hear what you think of this idea!

Kind regards,
Deev

**Comment by freddyz** [comment]
Hi Deev, If I'm understanding correctly, the problem you are experiencing is caused by Father & Son always outputting a 16-channel polyphonic signal regardless of the channel count of the input.  I agree that this behavior is undesirable, and I have already made the following change to the module (not yet in the plugin manager - if you can check out this repository and build from source you can test it yourself):
-Each output channel of Father & Son will output a signal that has the same number of channels as the largest "active" input.  For example, if input 1 & 2 are active, and both have 2 poly channels, the output will have 2 poly channels.  If input 1 has 3 poly channels, and input 2 has 1 poly channel, the output will have 3 poly channels.

A question for you:  If you place a Split module after the Father & Son output, and then use just channel 1 from the Split, does Father & Son work as you expect?  I expect it to behave exactly the same as Mental Patch Matrix.

I think that your idea of manually setting the output channel count would be useful, so I will add a right-click menu option for the next release.

**Comment by Deevje** [comment]
Hey, thanks for your quick reply!

The change to the number of polyphonic channels you mention sounds like a good one, that would probably mean that as long as I'm working monophonically, all outputs are monophonic, right?
I hadn't thought of the possibility of using a Split module since I haven't done much with polyphony yet., I just tried your suggestion, and everything reacts as I expect when I use the first channel of the Split module, only downside is that I would have to put a Split on every channel, which in most of my setups would amount to 16-20 extra modules :) so the manual setting will be a great shortcut!

Thanks again for taking the time and listening to crowd suggestions!

Kind regards
Deev

**Comment by freddyz** [comment]
> The change to the number of polyphonic channels you mention sounds like a good one, that would probably mean that as long as I'm working monophonically, all outputs are monophonic, right?

Yes that is correct.  I'm planning on having a right-click menu with these options for polyphony:
- Automatic (will use the proper number of poly channels as determined by the inputs.  If working with all monophonic signals, all Father & Son outputs will be mono as well)
- 16 options for manually setting to 1-16 channels (current behavior that you are seeing is the same as setting this to "16")

Thanks for the suggestion!

**Comment by freddyz** [comment]
Computerscare Modules 1.2.0 should now be available in the plugin manager.  Thanks @Deevje !
